# Generated by Django 6.0.8 on 2026-10-01 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('merchant', 'Merchant'), ('description', 'Description')], default='merchant', max_length=12)),
                ('pattern', models.CharField(help_text="Case-insensitive 'contains' match.", max_length=80)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower runs first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ledger.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.BinaryField()),
                ('trained_at', models.DateTimeField()),
                ('samples', models.PositiveIntegerField()),
                ('classes', models.PositiveSmallIntegerField()),
                ('accuracy', models.FloatField(blank=True, help_text='Cross-validated accuracy.', null=True)),
                ('corrections_since_training', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
