# Generated by Django 6.0.8 on 2026-10-01 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('auto_categorized', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('date_order', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='ledger.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
